### ISSUE TITLE
After update to latest version Magento throws error

### ISSUE THREAD

**Issue by Dieudon** [mageplaza/magento-2-dutch-language-pack#6]
Today I had to perform a composer update action after which Magento could not compile the Language files anymore.

The thrown error is:

```
a:4:{i:0;s:122:"Notice: Undefined offset: 1 in vendor\magento\framework\App\Language\Dictionary.php on line 199";i:1;s:10199:"#0 vendor\magento\framework\App\Language\Dictionary.php(199): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', 'vender\\magento\\f...', 199, Array)
#1 vendor\magento\framework\App\Language\Dictionary.php(113): Magento\Framework\App\Language\Dictionary->readPackCsv('mageplaza', 'nl_nl')
#2 vendor\magento\framework\Translate.php(325): Magento\Framework\App\Language\Dictionary->getDictionary('nl_NL')
#3 vendor\magento\framework\Translate.php(181): Magento\Framework\Translate->_loadPackTranslation()
#4 vendor\magento\framework\App\Area.php(240): Magento\Framework\Translate->loadData(NULL, false)
#5 vendor\magento\framework\App\Area.php(211): Magento\Framework\App\Area->_initTranslate()
#6 vendor\magento\framework\App\Area.php(138): Magento\Framework\App\Area->_loadPart('translate')
```
After some debugging it seems the cause is the empty line at the end of the csv file.
Please fix this issue...

The same issue with German and French language packs.
The used Magento version is 2.1.7.

Thanks for any help...

**Comment by imsamthomas** [comment]
Hi Dieudon,

We are working on the issue at https://github.com/mageplaza/magento-2-german-language-pack/issues/1

**Comment by imsamthomas** [comment]
Hi,
I have fixed the issue by removing the `github_contributions.csv` temporarily.
We will delivery the completed solution soon.
